Q1. What is the total revenue generated by male vs. female customers?
SELECT "Gender",
SUM("Purchase Amount (USD)") AS revenue 
FROM customer
group by "Gender";

Q2. Which customers used a discount but still spent more than the average purchase 
amount?
SELECT "Customer ID", "Purchase Amount (USD)"
FROM customer
WHERE "Discount Applied" = 'Yes' 
AND "Purchase Amount (USD)" >= (SELECT AVG("Purchase Amount (USD)") FROM customer);

Q3. Which are the top 5 products with the highest average review rating?
SELECT "Item Purchased" ,AVG("Review Rating") AS "AVERAGE CUSTOMER RATING" 
FROM customer 
GROUP BY "Item Purchased"
ORDER BY AVG("Review Rating") DESC
LIMIT 5;

Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT "Shipping Type", ROUND(AVG("Purchase Amount (USD)"),2)
FROM customer
WHERE "Shipping Type" in ('Standard','Express')
GROUP BY "Shipping Type";

Q5. Do subscribed customers spend more? 
Compare average spend and total revenue between subscribers and non-subscribers.

SELECT "Subscription Status",COUNT("Customer ID") as "count of customers",
AVG("Purchase Amount (USD)") as "average",
SUM("Purchase Amount (USD)") as "total revenue"
from customer
group by "Subscription Status"
Order by "total revenue","average" desc;

Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT "Item Purchased",
ROUND(100 * SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY "Item Purchased"
ORDER BY discount_rate DESC
LIMIT 5;
Q7. Segment customers into New, Returning, and Loyal based on 
their total number of previous purchases, and show the count of each segment.

WITH customer_type AS (
SELECT "Customer ID","Previous Purchases",
CASE WHEN "Previous Purchases" = 1 THEN 'New'
     WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
     ELSE 'Loyal'
     END AS "Customer Segment"
    FROM customer
)

SELECT "Customer Segment",
       COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY "Customer Segment";
Q8. What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT "Category",
           "Item Purchased",
           COUNT("Customer ID") AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY "Category"
               ORDER BY COUNT("Customer ID") DESC
           ) AS item_rank
    FROM Customer
    GROUP BY "Category", "Item Purchased"
)

SELECT item_rank,
       "Category",
       "Item Purchased",
       total_orders
FROM item_counts
WHERE item_rank <= 3; 

Q9. Are customers who are repeat buyers 
(more than 5 previous purchases) also likely to subscribe?

SELECT "Subscription Status",
       COUNT("Customer ID") AS repeat_buyers
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";

Q10. What is the revenue contribution of each age group?
SELECT "Age",
SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY "Age"
ORDER BY total_revenue DESC;